In [2]:
import numpy as np

## DataTypes and Attributes

In [41]:
# Numpy data type is ndarray (n dimensional array)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [42]:
a2 = np.array([[1,2,3],
               [4,5,6]
              ])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2.shape

(2, 3)

In [43]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]
               ]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a3.shape

(2, 3, 3)

In [16]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [17]:
# Create a DataFrame from a Numpy array

In [20]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## Creating NumPy arrays 

In [21]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int64')

In [24]:
ones = np.ones((2,3))

In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [28]:
zeros = np.zeros((2,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
range_array = np.arange(0, 100, 4)
range_array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [11]:
random_array = np.random.randint(0,10,size=(3,3,3))
random_array

array([[[8, 7, 3],
        [5, 2, 2],
        [4, 4, 6]],

       [[0, 5, 1],
        [4, 3, 5],
        [4, 0, 3]],

       [[2, 4, 6],
        [0, 5, 0],
        [3, 6, 2]]])

In [12]:
random_array.size

27

In [13]:
random_array.shape

(3, 3, 3)

In [16]:
random_array_2 = np.random.random((3,3))
random_array_2

array([[0.47976577, 0.68696211, 0.87191557],
       [0.61419288, 0.98958878, 0.76242256],
       [0.50528312, 0.89295055, 0.60410425]])

In [18]:
random_array_2.shape

(3, 3)

In [19]:
random_array_2.size

9

In [51]:
random_array_3= np.random.rand(2,3,4)
random_array_3

array([[[0.0871293 , 0.0202184 , 0.83261985, 0.77815675],
        [0.87001215, 0.97861834, 0.79915856, 0.46147936],
        [0.78052918, 0.11827443, 0.63992102, 0.14335329]],

       [[0.94466892, 0.52184832, 0.41466194, 0.26455561],
        [0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
        [0.6176355 , 0.61209572, 0.616934  , 0.94374808]]])

In [37]:
#Pseudo random number
np.random.seed(seed=0)
random_array_locked = np.random.randint(2,15,size=(3,3,3))
random_array_locked

array([[[14,  7,  2],
        [ 5, 13,  5],
        [ 9, 11,  5]],

       [[ 7,  4,  6],
        [ 9,  8, 10],
        [10, 14, 12]],

       [[ 3,  8,  9],
        [ 9, 10,  3],
        [ 7, 11, 10]]])

## Viewing arrays and matrices

In [39]:
#find unique elements in an array
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
a1

array([1, 2, 3])

In [50]:
a1[0]

1

In [45]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a2[0]

array([1, 2, 3])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a3[:2,:3,:1]

array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]]])

In [58]:
a4 = np.random.randint(10, 22, size=(2,3,4,5))
a4

array([[[[19, 20, 20, 18, 11],
         [11, 17, 19, 19, 13],
         [16, 17, 21, 12, 21],
         [10, 13, 15, 19, 20]],

        [[14, 21, 14, 16, 14],
         [14, 13, 14, 14, 18],
         [14, 13, 20, 17, 15],
         [15, 10, 11, 15, 19]],

        [[13, 10, 15, 10, 11],
         [12, 14, 12, 10, 13],
         [12, 20, 10, 17, 15],
         [19, 10, 20, 12, 21]]],


       [[[20, 17, 21, 12, 19],
         [12, 13, 21, 13, 12],
         [13, 14, 11, 12, 21],
         [19, 20, 11, 14, 20]],

        [[16, 21, 18, 21, 12],
         [13, 10, 10, 16, 10],
         [16, 13, 20, 13, 18],
         [18, 18, 12, 13, 12]],

        [[21, 10, 18, 18, 13],
         [18, 20, 12, 18, 14],
         [13, 10, 14, 13, 21],
         [16, 19, 21, 18, 10]]]])

In [60]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [64]:
# get the first number from the inner most array
a4[:,:,:,:1]

array([[[[19],
         [11],
         [16],
         [10]],

        [[14],
         [14],
         [14],
         [15]],

        [[13],
         [12],
         [12],
         [19]]],


       [[[20],
         [12],
         [13],
         [19]],

        [[16],
         [13],
         [16],
         [18]],

        [[21],
         [18],
         [13],
         [16]]]])

## Manipulating and comparing arrays

### Arithmetic

In [65]:
a1

array([1, 2, 3])

In [67]:
ones_2 = np.ones(3)
ones_2

array([1., 1., 1.])

In [68]:
 a1 + ones_2

array([2., 3., 4.])

In [69]:
a1 - ones_2

array([0., 1., 2.])

In [70]:
a1 * ones_2

array([1., 2., 3.])

In [71]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])